### ISSUE TITLE
Fails to run gakubuchi without Haml

### ISSUE THREAD

**Issue by 5t111111** [yasaichi/gakubuchi#4]
I've installed gakubuchi and found both "generator" and "rails server" fail to run without Haml installed.

```
$ bin/rails generate gakubuchi:install
/path/to/active_support/dependencies.rb:274:in `require': cannot load such file -- haml (LoadError)
```

```
$ bin/rails s
...
/path/to/active_support/dependencies.rb:274:in `require': cannot load such file -- haml (LoadError)
```

I don't know the root cause of the problem yet, but I thought the expected behavior is that a `NameError` occurs in [engine_registrar.rb](https://github.com/yasaichi/gakubuchi/blob/master/lib/gakubuchi/engine_registrar.rb#L21-L25) when you don't install Haml (`haml-rails`) . However, even if you don't need Haml at all, in fact `LoadError` is thrown in `constantize` process in the above code.

Dirty and rough workaround for me (using Slim) is either one of:

- Simply remove [this line](https://github.com/yasaichi/gakubuchi/blob/master/lib/gakubuchi/railtie.rb#L6)
- Rescue `LoadError` in addition to `NameError` on `constantize` method.

What is the good way to solve this problem? 

FYI: I've confirmed that the same error occurred on both Rails 4.2.6 and 5.0.0.beta3, and I can also provide full backtraces if you want.

Thanks in advance.

**Comment by yasaichi** [comment]
@5t111111
Thank you for your feedback.

When I created an test app with Rails 4.2.6 and gakubuchi 1.2.1, I faced the same error 😢 
Then, as far as I looked over the stack trace, I found it had been missed for the following reasons.

1. Rails app depends on `tilt` by default because `sass-rails` depends on `tilt`. Therefore, we can call `"::Tilt::HamlTemplate".constantize`.
2. [Tilt](https://github.com/rtomayko/tilt) doesen't depend on any gems, but calls `require 'haml'` in [Tilt::HamlTemplate](https://github.com/rtomayko/tilt/blob/master/lib/tilt/haml.rb#L2).
3. Gakubuchi's development dependencies include `haml-rails` and `slim-rails`.
4. For these reasons, we've missed this bug since v1.2.0.

Now that I've described the reasons, I'll answer your questions.

> What is the good way to solve this problem? 

OK, I feel

> Rescue `LoadError` in addition to `NameError` on `constantize` method.

is better than the other.

While I'll do it as soon as possible, I'm looking forward to your pull requrest 👍

**Comment by 5t111111** [comment]
@yasaichi Thank you for details 😄 

Expanding the exception class to the ancestor one would be pretty easy fix, so I'm willing to send you a pull request.

However, you know catching wider exceptions is kind of something should be avoided, moreover, since in most use-cases you don't want to use both Haml and Slim at once, leaving users to choose a template engine they want to use would make sense.

What I mean is that I think you can get rid of template engine registrations from `railtie.rb`, and you can add them in the initializer like the followings:

__railtie.rb__

```ruby
module Gakubuchi
  class Railtie < ::Rails::Railtie
    rake_tasks do
      ::Dir.glob(::File.expand_path('../../tasks/*.rake', __FILE__)).each { |path| load path }
    end
  end
end
```

__gakubuchi.rb.erb__

```erb
Gakubuchi.configure do |config|

  ~*~* snip ~*~*

end

Rails.application.config.assets.configure do |env|
  engine_registrar = Gakubuchi::EngineRegistrar.new(env)

  # Choose the template engine you prefer for writing static pages
  # (only Haml or Slim for the moment).
  <%- if options.engine.blank? -%>
  engine_registrar.register(:haml, '::Tilt::HamlTemplate')
  engine_registrar.register(:slim, '::Slim::Template')
  <%- elsif options.engine == 'haml' -%>
  engine_registrar.register(:haml, '::Tilt::HamlTemplate')
  # engine_registrar.register(:slim, '::Slim::Template')
  <%- elsif options.engine == 'slim' -%>
  # engine_registrar.register(:haml, '::Tilt::HamlTemplate')
  engine_registrar.register(:slim, '::Slim::Template')
  <%- end -%>
end
```

then add kind of this to `install_generator.rb` .

```ruby
      class_option :engine,
        type: :string,
        aliases: '-e',
        desc: 'Template engine to use'
```

How does this fix sound to you?

**Comment by yasaichi** [comment]
@5t111111 
Sorry for taking long to write you back, and thank you for your code snippets 🙇 
They gave me inspired a lot.

To come right to the point, I think we should fix this bug by catching wider exceptions
and then close this issue, because:

1. The bug is so fatal that it should be released as soon as possible
2. We have to consider how to implement your idea more

Since you would agree to the first, I'll explain the second.

First, I agree with you on this point:

> since in most use-cases you don't want to use both Haml and Slim at once, leaving users to choose a template engine they want to use would make sense.

So I'd like to release it as v2 since to specifiy a engine explicitly isn't compatible with the current version.

Next, let me tell how to support Haml and Slim.
Now Gakubuchi supports them by the following way: 

* Sprockets 2 and 3 support template engines which have the same interface as [Tilt](https://github.com/rtomayko/tilt) engine's
* Of course their interfaces are same as it
* Therefore, all we have to do is to call `register_engine` in `railtie.rb`

Unfortunately, however, Sprockets 4 (currently beta released) doesn't support it at all ([ref](https://github.com/rails/sprockets/tree/v4.0.0.beta2#processor-interface)).
Therefore, soon we have to fix the architecture of `Gakubuchi::EngineRegistrar` and so on,
which would be also incompatible change.

For that reason, I think your idea is good, but it should be implemented considering Sprockets 4.

**Comment by 5t111111** [comment]
Thank you for the detailed information and I am so grateful for fixing the issue.

I agree with your comments, that fix is fair enough for the moment (I didn't know Sprockets 4 includes such a big breaking change :cold_sweat:)

Anyway, I am looking forward to a new version of Gakubuchi 🎉
